-- ALTER USE TO ADD , DROP COLUMN , RENAME TABLE AND COLUMN & MODIFY TABLE 


USE STUDENTS;
 
 DROP TABLE IF EXISTS STUDENTS;
 
 CREATE TABLE STUDENTS (
  ROLLNO INT PRIMARY KEY,
  NAME VARCHAR(50),
 MARKS INT NOT NULL,
 GRADE VARCHAR(1),
 CITY VARCHAR(50) );
 

 
 INSERT INTO STUDENTS
  ( ROLLNO, NAME, MARKS, GRADE, CITY)
  VALUES
  (41, "anil", 78, "c", "pune"),
  (42, "bhumika", 93, "a", "mumbai"),
  (43, "chetan", 85, "b", "mumbai"),
  (44, "dhruv", 96, "A", "delhi" ),
  (45, "emanuel", 12, "f", "delhi"),
  (46 , "farah" , 82, "b", "delhi");
  
  SELECT * FROM STUDENTS;
  
  
  ALTER TABLE STUDENTS   
  ADD COLUMN AGE INT NOT NULL DEFAULT 19;  -- (YHA PE AGE COLUMN ADD HUA )
  
  
  ALTER TABLE STUDENTS
  MODIFY COLUMN AGE VARCHAR(2); -- YHA PE MODIFY KIYE COLUMN KA DATATYPE FROM INT TO VARCHAR 
  
  
  INSERT INTO STUDENTS
  (ROLLNO, NAME, MARKS, STU_AGE)
  VALUES
  (47, "BOB", 68, 100); -- YHA ERROR AYEGA QKI AGE 100 HAI BUT DATATYPE VARCHAR MAI LIMIT 2 HAI TO ISKO RUN KARNE KE TYPE KO MODIFY KRENGE MODIFY KRNE KE LIYE HM CHANGE COLUMN KO USE KRENGE
  
  
  
  
  
  
  ALTER TABLE STUDENTS
  CHANGE AGE STU_AGE INT; -- YHA PE AGE KA NAME CAHNGE HO GAYA AGE TO STU_AGE OR ISKA DATATYPE BHI VARCHAR SE INT MAI WAPAS LE AAE
  
  ALTER TABLE STUDENTS
  DROP COLUMN STU_AGE ; -- ( YHA PE STU_AGE COLUMN DELETE HO GAYA )
  
  
  
  
  
  ALTER TABLE STUDENTS
  RENAME TO STU; -- TABLE NAME CAHNGE HO GAYA STUDENT TO STU
  
  ALTER TABLE STU
  RENAME TO STUDENTS;  -- TABLE KA NAME WAPAS SE STU SE STUDENTS KAR DIYE