CREATE DATABASE IF NOT EXISTS STUDENTS;
 USE STUDENTS;
 
 DROP TABLE IF EXISTS STUDENTS;
 
 CREATE TABLE STUDENTS (
  ROLLNO INT PRIMARY KEY,
  NAME VARCHAR(50),
 MARKS INT NOT NULL,
 GRADE VARCHAR(1),
 CITY VARCHAR(50) );
 

 
 INSERT INTO STUDENTS
  ( ROLLNO, NAME, MARKS, GRADE, CITY)
  VALUES
  (41, "anil", 78, "c", "pune"),
  (42, "bhumika", 93, "a", "mumbai"),
  (43, "chetan", 85, "b", "mumbai"),
  (44, "dhruv", 96, "A", "delhi" ),
  (45, "emanuel", 12, "f", "delhi"),
  (46 , "farah" , 82, "b", "delhi");
  
  SELECT * FROM STUDENTS WHERE MARKS > 80;   -- KISSI EK LINE TO HI PRINT KRENGE SAB KRENGE TO ERROR AA AJYEGA QKI SAB KA CONDITIONS ALAG HAI. 
  SELECT * FROM STUDENTS WHERE CITY = "MUMBAI";  -- WHERE CLAUSE
  SELECT * FROM STUDENTS WHERE MARKS +10 > 100; -- ARTIHMETICAL OPERATORS
  SELECT * FROM STUDENTS WHERE MARKS = 93;  -- COMPARISON OPERATORS
  SELECT * FROM STUDENTS WHERE MARKS > 90 AND CITY = "MUMBAI" ; -- LOGICAL OPERATORS
  SELECT * FROM STUDENTS WHERE MARKS > 90 OR CITY = "MUMBAI" ; -- LOGICAL OPERATORS
  SELECT * FROM STUDENTS WHERE MARKS BETWEEN 80 AND 90; -- LOGICAL OPERATORS
  SELECT * FROM STUDENTS WHERE CITY IN ("DELHI" , "MUMBAI", "GURGAON" ); -- LOGICAL OPERATORS ( ISMAI WO BHI VALUE LIKH SAKTEY H JO HAI BHI NHI JAISE GURGAON, AGAR SIRF GURGAON LIKHTEY PHIR BHI OUTPUT MILTA BUT WO OUT PUT MAI NULL ATTA--
  SELECT * FROM STUDENTS WHERE CITY NOT IN ("DELHI" , "MUMBAI" );  -- JO MUMBAI & DELHI KE NHI H WO OUTPUT MAI SHOW HONGE JAISE HHAMARE TABLE MAI ANIL PUNE 
   SELECT * FROM STUDENTS LIMIT 3 ; -- STARTING KE 3 STUDENTS KA DATA PRINT HO JAYEGA LIMIT CLAUSE
  SELECT * FROM STUDENTS  WHERE MARKS > 75 LIMIT 3; --  HM CAHE TO LIMIT MAI BHI CODITION LGA SAKTEY HAI .
  SELECT * FROM STUDENTS ORDER BY CITY ASC; -- ORDER BY CLAUSE YHA ASC KA MTLB HAI JO CITY KA ALPHABET PEHLE AYEGA PEHLE WO PRINT HOGA HAMARE TABLE MAI PEHLE DELHI QKI D M SE PEHLE ATTA HAI JO DELHI MUMBAI AND PUNE KE PEHLE AYEGA.
  SELECT * FROM STUDENTS ORDER BY MARKS DESC; -- PEHLE SABSE JADA MARKS WALA AYEGA THEN USSE KAM 
  SELECT * FROM STUDENTS ORDER BY MARKS DESC LIMIT 3; -- TOP 3 STUDENTS KE MARKS AA JAYENGE
  SELECT  MAX(MARKS) FROM STUDENTS; -- AGGREGATE FUNCTIONS ( THIS LINES FOR GET MAX MARKS)
  SELECT MIN(MARKS) FROM STUDENTS; -- AGGREGATE FUNCTIONS ( THIS LINES FOR GET MIN MARKS)
  SELECT AVG(MARKS) FROM STUDENTS; -- AGGREGATE FUNCTIONS ( THIS LINES FOR GET AVG MARKS)
 SELECT COUNT(ROLLNO) FROM STUDENTS; -- AGGREGATE FUNCTIONS ( THIS LINE FOR HOW MANY STUDENTS IN CLASS AND ROLL NUMBER DEFINE MORE ACCURATE COUNT OF STUDENT CZ ROLL NO IS UNIQUE IT CANT MATCH WITH OTHER STUDNTS LIKE NAME
 SELECT CITY, COUNT(NAME) FROM STUDENTS GROUP BY CITY; -- GROUP BY CALUSE AND GENERALLY WE USE GROUP BY CLAUSE WITH AGGREGATE FUNCTION (HERE WE USE COUNT AGGEREGATE FUCNCTION) THIS LINE TO COUNT NUMBER OF STUDENTS IN EACH CITY.
 SELECT CITY, NAME,  COUNT(ROLLNO) FROM STUDENTS GROUP BY CITY, NAME;-- ISSBAAR CITY AND NAME DONO KE BASIS PE GROUP BANEGA
 SELECT CITY, AVG(MARKS) FROM STUDENTS GROUP BY CITY ; -- CITYWISE STUDENTS KE AVG MARKS
 
 
 
 select  city, count(rollno) from students group by city having max (marks) > 90; -- having caluse
 
 
 
 
 
 select city
 from students
 where grade = "a"  -- grade a ka condition sare rows pe lga
 group by city
 having max(marks) >= 75 -- having condition group pe lga 
 order by city asc ;
 
SET SQL_SAFE_UPDATES = 0;




-- UPDATE COMMAND
 update students 
 set grade = "o"
 where grade = "a";
 
 SELECT * FROM STUDENTS;
 
 
 -- TO UPDATE MARKS OF EMANUEL FROM 12 TO 82
 UPDATE STUDENTS
 SET MARKS = 82
 WHERE ROLLNO = 45 ;
 
 -- TO UPDATE EMANUEL GRADE ACCORDING TO HIS CORRECT MARKS(82)
 UPDATE STUDENTS
 SET GRADE = "B"
 WHERE MARKS BETWEEN 80 AND 90 ;
 
 
 -- MARKS AGAR SARE STUDENTS KO COLLEGE KE TARAF SE 2 MARKS EXTRA DENA HAI 
 UPDATE STUDENTS
 SET MARKS = MARKS +2;
 
 
 -- HUM DUWARA SE EMANUAEL KE MARKS 12 KAR DETE HAI 
 UPDATE STUDENTS
 SET MARKS = 12
 WHERE ROLLNO = 45;
 
 
 
 
 -- DELETE COMMAND
 
 DELETE FROM STUDENTS
 WHERE MARKS < 33; -- EMANUAEL TABLE SE DELETE HO GAYA QKI USKA MARKS 12 THA
 
 -- DELETE KA USE CAREFULLY KARNA HAI QKI AGAR DELETE KARDIYA TO WO WAPAS NHI MILEGA DATA BASE MAI 
 -- AGAR HM CMND DETE DELETE FROM STUDENTS TO SARA TABLE HI DELETE HO JATA IOR WO WPS RECOVER BHI NHI HOGA TO DELETE KA USE CEAREFULLY KARNA HAI
 
 
 
 
 
 
 