use college;

CREATE TABLE DEPT (    -- DEPT :- DEPARTMENT
ID INT PRIMARY KEY,
NAME VARCHAR(50)
);

CREATE TABLE TEACHERS (
 ID INT PRIMARY KEY,
 NAME VARCHAR(50),
 DEPT_ID INT,
 FOREIGN KEY (DEPT_ID) REFERENCES DEPT(ID)
 ON UPDATE CASCADE  -- AGAR KISSI CHIZ MAI BHI UPDATE YA DLETE NHI KARNA HOGA TO ON UPDATE AND ON DELETE CASCADE USE NHI KRENGE 
 ON DELETE CASCADE
 );
 
 
 INSERT INTO DEPT
 VALUES
 (101, "ENGLISH" ),
 (102, "IT" );
 
 UPDATE DEPT
 SET ID = 111
 WHERE ID = 103;
 
 
 
 SELECT * FROM DEPT ;
 
 
 INSERT INTO TEACHERS
 VALUES
 (101, "ADAM", 101),
 (102, "EVE", 102);
 
 
 SELECT  * FROM TEACHERS;
 
 
 -- HM PARENT TABLE (DEPT ) MAI UPDATE KIYE TO CHILD TABLE (TEACHERS) MAI BHI CUPDATE HO JAYEGA 
 
 
 
 
 