use college;

CREATE TABLE STUDENTS (
 ID INT PRIMARY KEY,
 NAME VARCHAR(50)
 );
 
 
 INSERT INTO STUDENTS (ID, NAME)
   VALUES
   (101, "ADAM"),
   (102, "BOB" ),
   (103, "CASEY");
 
CREATE TABLE COURSE (
ID INT PRIMARY KEY,
COURSE VARCHAR(50)
);


INSERT INTO COURSE (ID, COURSE)
VALUES
(102, "ENGLISH"),
(105, "MATHS"),
(103, "SCIENCE"),
(107, "COMPUTER_SCIENCE");

SELECT * FROM STUDENTS;
SELECT * FROM COURSE;



-- INNER JOIN IT WILL SHOW COMMON DATA FROM BOTH TABLE AS RESULT
SELECT *
FROM STUDENTS AS A
INNER JOIN COURSE AS C
ON A.ID = C.ID;
-- ALIAS STUDENTS AS A AND COURSE AS C HM ALIAS USE KAR SAKTEY HAI JAB TABLE KA NAME BAHUT BDA HO TO.




-- LEFT JOIN ( LEFT TABLE KA SARA DATA SHOW KREGA AND RIGHT TABLE MAI JO BHI LEFT TABLE SE COMMON DATA HOGA SIRF UNHI COMMON DATA KO SHOW KREGA).

SELECT *
FROM STUDENTS AS A
LEFT JOIN COURSE AS C
ON A.ID = C.ID;



-- RIGHT JOIN    (RIGHT TABLE KA SARA DATA SHOW KREGA AND LEFT TABLE MAI JO BHI RIGJHT TABLE SE COMMON DATA HOGA SIRF UNHI COMMON DATA KO SHOW KREGA).

SELECT *
FROM STUDENTS AS A
RIGHT JOIN COURSE AS C
ON A.ID = C.ID;



-- FULL JOIN   ( DONO TABLE KE DATA KO DEKHYEGA AND JO DATA DONO TABLE MAI COMMON HOGA USS DATA KO SINGLE TIME HI DEKHYEGA)


 SELECT * 
 FROM STUDENTS AS S
 LEFT JOIN COURSE AS C
 ON S.ID = C.ID
 UNION
SELECT *
FROM STUDENTS AS A
RIGHT JOIN COURSE AS C
ON A.ID = C.ID;




-- LEFT EXCLUSIVE DATA ( LEFT TABLE KA SARA DATA DEGA AND JO DATA LEFT & RIGHT DATA MAI COMMON HOGA WO RSLT  MAI NHI DEGA)


SELECT *
FROM STUDENTS AS S
LEFT JOIN COURSE AS C
ON S.ID = C.ID
WHERE C.ID IS NULL;


-- RIGHT EXCLUSIVE DATA ( RIGHT TABLE KA SARA DATA DEGA AND JO DATA LEFT & RIGHT DATA MAI COMMON HOGA WO RSLT  MAI NHI DEGA)



SELECT *
FROM STUDENTS AS S
RIGHT JOIN COURSE AS C
ON S.ID = C.ID
WHERE S.ID IS NULL; 



-- SELF JOIN ( 1 TABLE KO USSI KE SATH JOIN KARTA HAI)

CREATE TABLE EMPLOYEE (
 ID INT PRIMARY KEY,
 NAME VARCHAR(50),
 MANAGER_ID int
 );
 
INSERT INTO EMPLOYEE (ID, NAME, MANAGER_ID)
VALUES
(101, "ADAM", 103),
(102, "BOB", 104),
(103, "CASEY", NULL),
(104, "DONALD", 103);

SELECT * FROM EMPLOYEE;

SELECT A.NAME AS MANAGER_NAME, B.NAME
FROM EMPLOYEE AS A
JOIN EMPLOYEE AS B
ON A.ID = B.MANAGER_ID;


--  UNION SARE DUPLICATES KO HTA KE UNIQUE DATA DETA HAI 
SELECT NAME FROM EMPLOYEE
UNION 
SELECT NAME FROM EMPLOYEE;  

-- UNION ALL SARA DATA DETA HAI DUPLICATE BHI 
SELECT NAME FROM EMPLOYEE
UNION ALL
SELECT NAME FROM EMPLOYEE;  








