-- WRITE A QUERY TO FIND AVG MARKS IN EACH CITY IN ASCENDING ORDER.
CREATE DATABASE IF NOT EXISTS QUESTION_2;
 USE QUESTION_2;
 
 DROP TABLE IF EXISTS QUESTION_2;
 
 CREATE TABLE PRACTICE_QS(
  ROLLNO INT PRIMARY KEY,
  NAME VARCHAR(50),
 MARKS INT NOT NULL,
 GRADE VARCHAR(1),
 CITY VARCHAR(50) );
 

 
 INSERT INTO PRACTICE_QS
  ( ROLLNO, NAME, MARKS, GRADE, CITY)
  VALUES
  (41, "anil", 78, "c", "pune"),
  (42, "bhumika", 93, "a", "mumbai"),
  (43, "chetan", 85, "b", "mumbai"),
  (44, "dhruv", 96, "A", "delhi" ),
  (45, "emanuel", 12, "f", "delhi"),
  (46 , "farah" , 82, "b", "delhi");
  
  SELECT CITY, AVG (MARKS) FROM PRACTICE_QS GROUP BY CITY ORDER BY AVG(MARKS); -- ORDER BY MAY ASC DESC NHI LIKHENGE TO WO BY DEFAULT ASC ODER MAI RESULT DEGA YE ORDER BY KA PROPERTY HAI
    SELECT CITY, AVG (MARKS) FROM PRACTICE_QS GROUP BY CITY ORDER BY AVG(MARKS) DESC; -- DESC KE LIYE DESC LIKHNA PDA
    select grade, count(rollno) from practice_qs group by grade order by grade;