-- CREATE A DATABSE FOR YOUR COMPANY NAMED XYZ
CREATE DATABASE XYZ_COMPANY;
USE XYZ_COMPANY;
CREATE TABLE EMPLOEE(
  ID INT PRIMARY KEY,
  NAME VARCHAR(100),
  SALARY INT
  );
  
  INSERT INTO EMPLOEE
  (ID, NAME, SALARY)
  VALUES
  (1, "ADAM", 25000),
  (2, "BOB", 30000),
  (3, "CASEY", 40000);
  
  SELECT * FROM EMPLOEE;
  
  
  
  


  