 CREATE DATABASE IF NOT EXISTS TEACHVIMAN;
 USE TEACHVIMAN;
 
 DROP TABLE IF EXISTS MEMBERS;
 
 CREATE TABLE MEMBERS (
  ROLLNO INT PRIMARY KEY,
  NAME VARCHAR(50),
 MARKS INT NOT NULL,
 GRADE VARCHAR(1),
 CITY VARCHAR(50) );
 
 INSERT INTO MEMBERS
  ( ROLLNO, NAME, MARKS, GRADE, CITY)
  VALUES
  (31, "RISHU", 81, "B", "TARAPUR"),
  (28, "ROSHAN", 71, "C", "GAYA"),
  (32, "SABIR", 61, "D", "SEIKHPURA"),
  (14, "DEVIKA", 91, "A", "JAMUI" );
  
  SELECT NAME, MARKS FROM MEMBERS;
  
  SELECT * FROM MEMBERS;
  
  SELECT CITY FROM MEMBERS;
  
  SELECT DISTINCT CITY FROM MEMBERS;
  
  
  
